In [5]:
import pandas as pd
import numpy as np


df = pd.read_excel('GNP_in_each_region.xlsx')
df

c:\Users\PlayData\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,시도별,2006,2006.1,2006.2,2006.3,2007,2007.1,2007.2,2007.3,2008,...,2019.2,2019.3,2020,2020.1,2020.2,2020.3,2021 p),2021 p).1,2021 p).2,2021 p).3
0,시도별,1인당 지역내총생산,1인당 지역총소득,1인당 개인소득,1인당 민간소비,1인당 지역내총생산,1인당 지역총소득,1인당 개인소득,1인당 민간소비,1인당 지역내총생산,...,1인당 개인소득,1인당 민간소비,1인당 지역내총생산,1인당 지역총소득,1인당 개인소득,1인당 민간소비,1인당 지역내총생산,1인당 지역총소득,1인당 개인소득,1인당 민간소비
1,전국,20878,20817,12058,11074,22456,22399,12636,11780,23637,...,20661,18057,37515,37842,21342,17320,40125,40571,22220,18435
2,서울특별시,24420,27315,14008,13497,26478,30371,15023,14354,27894,...,23978,21991,46221,49006,24226,21185,49648,54209,25256,22613
3,부산광역시,15386,16272,11323,10441,16703,17592,11855,11172,18167,...,19723,18134,27204,29643,20460,17365,29649,32014,21352,18693
4,대구광역시,13580,15228,11193,10681,14558,15885,11503,11281,15049,...,19196,17964,23910,27934,20229,17276,25492,29353,21046,18378
5,인천광역시,18838,18100,10769,10083,20455,19729,11151,10831,19970,...,19582,16552,30367,32724,20310,16059,33287,35818,21317,17170
6,광주광역시,14938,15846,11389,10559,16116,17373,12137,11262,16525,...,20791,18326,28433,31674,21591,17602,29583,32999,22472,18829
7,대전광역시,15657,17010,11755,10847,16513,17867,12339,11502,17426,...,20648,18115,29757,32080,21707,17715,31362,33810,22730,19146
8,울산광역시,42229,34625,14426,11317,46310,38917,15502,12065,48794,...,22617,18574,60895,53908,23863,17816,69133,59346,25165,19211
9,세종특별자치시,-,-,-,-,-,-,-,-,-,...,20674,16845,36473,37869,21407,16158,37958,39730,22061,17198
10,경기도,18944,20593,12196,11104,20008,21415,12740,11882,20863,...,20746,17493,36521,38819,21220,16721,38720,41011,21937,17743
11,강원도,17498,16156,10530,9905,18832,17280,10863,10519,19593,...,19174,16905,32026,28891,20267,16193,33319,30858,21038,17077
12,충청북도,20474,17396,10840,9606,21923,18391,11247,10136,22378,...,18989,15885,42667,35403,20029,15215,45803,37903,21081,16097
13,충청남도,28760,21450,10994,10310,30667,22905,11365,10771,32648,...,19216,16123,53078,42073,20393,15426,57241,45544,21262,16319
14,전라북도,15965,15344,10922,9608,17195,16168,11387,10091,18355,...,18941,16103,29252,29515,19991,15351,30912,31157,20862,16156
15,전라남도,24303,20080,11110,9364,27407,21970,11424,10043,30160,...,19072,16199,43957,38605,19873,15441,49506,38857,20881,16251
16,경상북도,25983,21536,11202,9754,27165,22157,11391,10277,28945,...,18748,16311,39887,35471,19798,15473,42706,38000,20667,16453
17,경상남도,22087,19258,11611,10112,24063,20968,11967,10699,26038,...,19078,16520,33186,31550,19759,15890,33782,32968,20650,16981
18,제주특별자치도,16001,15659,11125,10408,17139,16350,11544,10989,17655,...,18815,17037,29334,30030,19954,16227,29781,31999,20475,17285

In [3]:
# df = df.reset_index(drop=True)

In [17]:
df1.columns[-1]

'2021 p)'

In [ ]:
df1 = df.iloc[1:, 1:66:4]
df1.index = df['시도별'][1:]

In [19]:
df1.to_excel('After_preprocessing/GNP_in_each_region.xlsx')