In [1]:
import pandas as pd
import numpy as np

In [17]:
df = pd.read_csv('Labor_Force_Participation_Rate.csv', encoding='CP949')

In [28]:
# df.columns = df.iloc[0]
df = df.drop(df.index[0], axis=0) # 데이터 정리 완료

In [36]:
list_to_append = []

for i in range(0, 284):
    list_to_append.append(df.index[i])

In [38]:
for i in range(0, 284):
    list_to_append[i] = list_to_append[i].replace('.', '-')

In [40]:
from datetime import datetime

for i in range(0, 284):
    list_to_append[i] = datetime.strptime(list_to_append[i], '%Y-%m')

In [41]:
df

시도별,계,서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별자치시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주도
1999.06,49.0,48.7,46.5,46.7,46.8,44.4,42.6,41.5,-,48.4,48.3,51.5,53.4,51.0,54.8,55.3,49.7,54.9
1999.07,48.7,48.9,47.0,45.9,46.0,45.5,42.9,40.6,-,47.0,48.8,50.6,53.9,51.1,53.5,54.4,50.4,55.8
1999.08,48.1,47.6,46.4,45.4,45.7,44.4,42.8,40.6,-,46.3,48.5,50.8,53.9,50.6,54.3,54.3,48.7,55.3
1999.09,49.2,48.5,47.7,47.5,47.0,45.4,43.9,41.6,-,47.7,49.1,52.0,54.5,49.8,55.3,55.5,50.4,56.8
1999.10,49.5,48.5,47.5,48.8,46.7,45.3,45.0,40.7,-,47.9,49.1,52.2,55.4,51.1,56.4,56.1,51.5,57.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022.09,55.1,55.0,50.2,52.5,55.9,52.1,53.6,49.1,53.3,55.3,59.4,57.3,58.0,57.3,61.2,54.7,53.4,66.1
2022.10,55.0,54.5,50.3,51.9,55.9,52.8,54.0,49.4,53.4,54.9,59.7,56.7,58.6,57.3,60.4,56.2,53.5,67.6
2022.11,55.1,54.9,50.5,51.8,56.9,52.7,54.3,49.5,53.9,55.0,59.2,56.6,57.5,56.8,60.5,55.2,54.1,68.4
2022.12,54.2,55.2,50.9,51.7,56.4,51.5,54.7,49.0,52.2,54.2,56.7,54.6,53.2,54.5,59.6,52.4,53.2,67.5
2023.01,53.6,55.0,50.4,51.4,55.2,52.2,54.4,48.8,53.1,53.3,55.2,53.1,51.7,53.8,59.3,51.7,52.3,63.3

In [42]:
df.to_excel('After_preprocessing/Labor_Force_Participation_Rate.xlsx')