In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

path = 'C:/playdata/To_raise_a_child_well/data/dohee/'
sum_df = pd.read_excel(path+'전국데이터프레임2006_2021.xlsx', index_col = 0)
sum_df

,실업률,이혼율,고령화비율,혼인건수,소비자물가지수,출산아수/가임기여성의수,아파트전세지수,미분양주택지수,은행예금지수,경제활동참가율,지가변동률
시점,,,,,,,,,,,
1999-06-01,5.6,0.001352,NaN,36243.0,61.349,NaN,NaN,NaN,NaN,49.0,NaN
1999-07-01,5.6,0.001913,NaN,25464.0,61.140,NaN,NaN,NaN,NaN,48.7,NaN
1999-08-01,5.0,0.002503,NaN,19217.0,61.765,NaN,NaN,NaN,NaN,48.1,NaN
1999-09-01,4.2,0.002985,NaN,16485.0,61.921,NaN,NaN,NaN,NaN,49.2,NaN
1999-10-01,4.0,0.002003,NaN,24713.0,62.389,NaN,NaN,NaN,NaN,49.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2022-09-01,2.5,NaN,17.8,NaN,108.930,0.001486,102.8,102.8,1958348.3,55.1,NaN
2022-10-01,2.4,NaN,17.9,NaN,109.210,0.001486,101.4,101.4,1967290.0,55.0,NaN
2022-11-01,2.3,NaN,17.9,NaN,109.100,0.001486,99.0,99.0,1970661.1,55.1,NaN
2022-12-01,3.5,NaN,18.0,NaN,109.280,0.001486,95.3,95.3,NaN,54.2,NaN
2023-01-01,4.1,NaN,18.1,NaN,110.100,0.001486,NaN,NaN,NaN,53.6,NaN

In [2]:
from sklearn.model_selection import train_test_split
x = sum_df.drop(['출산아수/가임기여성의수'], axis = 1).loc['2006-01-01' : '2021-12-01'].values
y = sum_df['출산아수/가임기여성의수'].loc['2006-01-01' : '2021-12-01']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=42)
x_train.shape, x_test.shape

((153, 10), (39, 10))

In [31]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

# 데이터 분리
from sklearn.model_selection import train_test_split
x = sum_df.drop(['출산아수/가임기여성의수'], axis = 1).loc['2006-01-01' : '2021-12-01'].values
y = sum_df['출산아수/가임기여성의수'].loc['2006-01-01' : '2021-12-01']
            
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=42)
x_train.shape, x_test.shape

# 데이터 프레임
knn_reg_df = pd.DataFrame(index = ['mse', 'rmse', 'r2'])
dt_reg_df = pd.DataFrame(index = ['mse', 'rmse', 'r2'])
rf_reg_df = pd.DataFrame(index = ['mse', 'rmse', 'r2'])

# max_depth, n_neighbor 파라미터 : i
for i in range(1, 6) : 
    # n_neighbor 파라미터 : j
    for j in range(10, 101, 10) :
        knn_reg = KNeighborsRegressor(n_neighbors = i)
        dt_reg = DecisionTreeRegressor(max_depth = i)
        rf_reg = RandomForestRegressor(max_depth = i, n_estimators = j)

        # 학습        
        knn_reg.fit(x_train, y_train)
        dt_reg.fit(x_train, y_train)
        rf_reg.fit(x_train, y_train)
        
        # 예측
        y_pred_knn = knn_reg.predict(x_test)
        y_pred_dt = dt_reg.predict(x_test)
        y_pred_rf = rf_reg.predict(x_test)
        
        # 모델 평가 및 데이터프레임, r2 최대값 출력
        from sklearn.metrics import mean_squared_error, r2_score
        # knn
        mse = mean_squared_error(y_test, y_pred_knn)  
        rmse = np.sqrt(mse)                       
        r2 = r2_score(y_test, y_pred_knn)    
        total = np.round((mse, rmse, r2), 3)
        
        knn_reg_df['n_neighbors='+str(i)] = total
        knn_reg_df
        
        # dt
        mse = mean_squared_error(y_test, y_pred_dt)  
        rmse = np.sqrt(mse)                       
        r2 = r2_score(y_test, y_pred_dt)    
        total = np.round((mse, rmse, r2), 3)
        
        dt_reg_df['max_depth='+str(i)] = total
        dt_reg_df
        
        # rf
        mse = mean_squared_error(y_test, y_pred_rf)  
        rmse = np.sqrt(mse)                       
        r2 = r2_score(y_test, y_pred_rf)    
        total = np.round((mse, rmse, r2), 3)
        
        rf_reg_df['max_depth='+str(i)+'n_estimators='+str(j)] = total
        rf_reg_df

In [32]:
knn_reg_df

,n_neighbors=1,n_neighbors=2,n_neighbors=3,n_neighbors=4,n_neighbors=5
mse,0.000,0.000,0.000,0.000,0.000
rmse,0.000,0.000,0.000,0.000,0.000
r2,0.782,0.903,0.898,0.914,0.918

In [33]:
dt_reg_df

      max_depth=1  max_depth=2  max_depth=3  max_depth=4  max_depth=5
mse         0.000        0.000        0.000        0.000        0.000
rmse        0.000        0.000        0.000        0.000        0.000
r2          0.679        0.869        0.904        0.903        0.885

In [34]:
rf_reg_df

,max_depth=1n_estimators=10,max_depth=1n_estimators=20,max_depth=1n_estimators=30,max_depth=1n_estimators=40,max_depth=1n_estimators=50,max_depth=1n_estimators=60,max_depth=1n_estimators=70,max_depth=1n_estimators=80,max_depth=1n_estimators=90,max_depth=1n_estimators=100,...,max_depth=5n_estimators=10,max_depth=5n_estimators=20,max_depth=5n_estimators=30,max_depth=5n_estimators=40,max_depth=5n_estimators=50,max_depth=5n_estimators=60,max_depth=5n_estimators=70,max_depth=5n_estimators=80,max_depth=5n_estimators=90,max_depth=5n_estimators=100
mse,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
rmse,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
r2,0.681,0.716,0.711,0.701,0.682,0.695,0.696,0.685,0.693,0.687,...,0.925,0.935,0.931,0.934,0.934,0.937,0.935,0.935,0.937,0.939

In [35]:
max(rf_reg_df.loc['r2'])

0.939

In [1]:
from sklearn.neighbors import KNeighborsRegressor
KNeighborsRegressor?

Init signature:
KNeighborsRegressor(
    n_neighbors=5,
    *,
    weights='uniform',
    algorithm='auto',
    leaf_size=30,
    p=2,
    metric='minkowski',
    metric_params=None,
    n_jobs=None,
)
Docstring:
Regression based on k-nearest neighbors.

The target is predicted by local interpolation of the targets
associated of the nearest neighbors in the training set.

Read more in the :ref:`User Guide <regression>`.

.. versionadded:: 0.9

Parameters
----------
n_neighbors : int, default=5
    Number of neighbors to use by default for :meth:`kneighbors` queries.

weights : {'uniform', 'distance'}, callable or None, default='uniform'
    Weight function used in prediction.  Possible values:

    - 'uniform' : uniform weights.  All points in each neighborhood
      are weighted equally.
    - 'distance' : weight points by the inverse of their distance.
      in this case, closer neighbors of a query point will have a
      greater influence than neighbors which are further away.
    - [callable] : a user-defined function which accepts an
      array of distances, and returns an array of the same shape
      containing the weights.

    Uniform weights are used by default.

algorithm : {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'
    Algorithm used to compute the nearest neighbors:

    - 'ball_tree' will use :class:`BallTree`
    - 'kd_tree' will use :class:`KDTree`
    - 'brute' will use a brute-force search.
    - 'auto' will attempt to decide the most appropriate algorithm
      based on the values passed to :meth:`fit` method.

    Note: fitting on sparse input will override the setting of
    this parameter, using brute force.

leaf_size : int, default=30
    Leaf size passed to BallTree or KDTree.  This can affect the
    speed of the construction and query, as well as the memory
    required to store the tree.  The optimal value depends on the
    nature of the problem.

p : int, default=2
    Power parameter for the Minkowski metric. When p = 1, this is
    equivalent to using manhattan_distance (l1), and euclidean_distance
    (l2) for p = 2. For arbitrary p, minkowski_distance (l_p) is used.

metric : str or callable, default='minkowski'
    Metric to use for distance computation. Default is "minkowski", which
    results in the standard Euclidean distance when p = 2. See the
    documentation of `scipy.spatial.distance
    <https://docs.scipy.org/doc/scipy/reference/spatial.distance.html>`_ and
    the metrics listed in
    :class:`~sklearn.metrics.pairwise.distance_metrics` for valid metric
    values.

    If metric is "precomputed", X is assumed to be a distance matrix and
    must be square during fit. X may be a :term:`sparse graph`, in which
    case only "nonzero" elements may be considered neighbors.

    If metric is a callable function, it takes two arrays representing 1D
    vectors as inputs and must return one value indicating the distance
    between those vectors. This works for Scipy's metrics, but is less
    efficient than passing the metric name as a string.

metric_params : dict, default=None
    Additional keyword arguments for the metric function.

n_jobs : int, default=None
    The number of parallel jobs to run for neighbors search.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
    Doesn't affect :meth:`fit` method.

Attributes
----------
effective_metric_ : str or callable
    The distance metric to use. It will be same as the `metric` parameter
    or a synonym of it, e.g. 'euclidean' if the `metric` parameter set to
    'minkowski' and `p` parameter set to 2.

effective_metric_params_ : dict
    Additional keyword arguments for the metric function. For most metrics
    will be same with `metric_params` parameter, but may also contain the
    `p` parameter value if the `effective_metric_` attribute is set to
    'minkowski'.

n_features_in_ : int
    Number of features seen during :term:`fit`.

    .. versionadded:: 0.24

feature_names_in_ : ndarray of shape (`n_features_in_`,)
    Names of features seen during :term:`fit`. Defined only when `X`
    has feature names that are all strings.

    .. versionadded:: 1.0

n_samples_fit_ : int
    Number of samples in the fitted data.

See Also
--------
NearestNeighbors : Unsupervised learner for implementing neighbor searches.
RadiusNeighborsRegressor : Regression based on neighbors within a fixed radius.
KNeighborsClassifier : Classifier implementing the k-nearest neighbors vote.
RadiusNeighborsClassifier : Classifier implementing
    a vote among neighbors within a given radius.

Notes
-----
See :ref:`Nearest Neighbors <neighbors>` in the online documentation
for a discussion of the choice of ``algorithm`` and ``leaf_size``.

.. warning::

   Regarding the Nearest Neighbors algorithms, if it is found that two
   neighbors, neighbor `k+1` and `k`, have identical distances but
   different labels, the results will depend on the ordering of the
   training data.

https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm

Examples
--------
>>> X = [[0], [1], [2], [3]]
>>> y = [0, 0, 1, 1]
>>> from sklearn.neighbors import KNeighborsRegressor
>>> neigh = KNeighborsRegressor(n_neighbors=2)
>>> neigh.fit(X, y)
KNeighborsRegressor(...)
>>> print(neigh.predict([[1.5]]))
[0.5]
File:           c:\users\playdata\appdata\roaming\python\python39\site-packages\sklearn\neighbors\_regression.py
Type:           ABCMeta
Subclasses: